--NICHOLAS SCHULER
--A11
--CIS31029




--TO DROP TABLES FROM THE DATABASE
DROP TABLE MEMBERSHIP
DROP TABLE RENTAL
DROP TABLE DETAILRENTAL
DROP TABLE VIDEO
DROP TABLE MOVIE
DROP TABLE PRICE



CREATE TABLE MEMBERSHIP
(
	MEM_NUM INT NOT NULL UNIQUE,
	MEM_FNAME VarChar (MAX) NOT NULL,      
	MEM_LNAME VarChar (MAX) NOT NULL,
	MEM_STREET VarChar (MAX) NOT NULL,
	MEM_CITY VarChar (MAX) NOT NULL,
	MEM_STATE CHAR (2) NOT NULL,
	MEM_ZIP CHAR (5) NOT NULL,
	MEM_BALANCE DECIMAL NOT NULL
);

CREATE TABLE RENTAL
(
	RENT_NUM INT NOT NULL UNIQUE,
	RENT_DATE DATETIME NOT NULL,
	MEM_NUM INT NOT NULL
);

CREATE TABLE DETAILRENTAL
(
	RENT_NUM INT NOT NULL,
	VID_NUM INT NOT NULL,
	DETAIL_FEE DECIMAL NOT NULL,
	DETAIL_DUEDATE DATETIME NOT NULL,
	DETAIL_RETURNDATE DATETIME,
	DETAIL_DAILYLATEFEE DECIMAL NOT NULL
);

CREATE TABLE VIDEO
(
	VID_NUM INT NOT NULL UNIQUE,
	VID_INDATE DATETIME NOT NULL,
	MOVIE_NUM INT NOT NULL
);

CREATE TABLE MOVIE
(
	MOVIE_NUM INT NOT NULL UNIQUE,
	MOVIE_TITLE VarChar (MAX) NOT NULL,
	MOVIE_YEAR INT NOT NULL,
	MOVIE_COST DECIMAL NOT NULL,
	MOVIE_GENRE VarChar (MAX) NOT NULL,
	PRICE_CODE INT NOT NULL
);

CREATE TABLE PRICE
(
	PRICE_CODE INT NOT NULL UNIQUE,
	PRICE_DESCRIPTION VarChar (MAX) NOT NULL,
	PRICE_RENTFEE DECIMAL NOT NULL,
	PRICE_DAILYLATEFEE DECIMAL NOT NULL
);




ALTER TABLE MEMBERSHIP
ADD CONSTRAINT PK_MEM_NUM PRIMARY KEY (MEM_NUM)

ALTER TABLE RENTAL
ADD CONSTRAINT PK_RENT_NUM PRIMARY KEY (RENT_NUM),
	CONSTRAINT FK_MEM_NUM FOREIGN KEY (MEM_NUM) REFERENCES MEMBERSHIP (MEM_NUM)

ALTER TABLE DETAILRENTAL
ADD CONSTRAINT PK_DETAILRENTAL PRIMARY KEY (RENT_NUM, VID_NUM),
	CONSTRAINT FK_DETAILRENTAL_RENT_NUM FOREIGN KEY (RENT_NUM) REFERENCES RENTAL (RENT_NUM),
	CONSTRAINT FK_RENTALDETAIL_VID_NUM FOREIGN KEY (VID_NUM) REFERENCES VIDEO (VID_NUM)

ALTER TABLE VIDEO
ADD CONSTRAINT PK_VID_NUM PRIMARY KEY (VID_NUM),
	CONSTRAINT FK_MOVIE_NUM FOREIGN KEY (MOVIE_NUM) REFERENCES MOVIE (MOVIE_NUM)

ALTER TABLE MOVIE 
ADD CONSTRAINT PK_MOVIE_NUM PRIMARY KEY (MOVIE_NUM),
	CONSTRAINT FK_PRICE_CODE FOREIGN KEY (PRICE_CODE) REFERENCES PRICE (PRICE_CODE)

ALTER TABLE PRICE
ADD CONSTRAINT PK_PRICE_CODE PRIMARY KEY (PRICE_CODE)




--TO TEST ALL DATA IS IN THE TABLES
SELECT * FROM MEMBERSHIP
SELECT * FROM RENTAL
SELECT * FROM DETAILRENTAL
SELECT * FROM VIDEO
SELECT * FROM MOVIE
SELECT * FROM PRICE


--44
ALTER TABLE DETAILRENTAL
ADD DETAIL_DAYSLATE DECIMAL(3)


--45
ALTER TABLE VIDEO
ADD VID_STATUS VARCHAR (4) NOT NULL DEFAULT 'IN',
	CONSTRAINT CHK_STATUS CHECK (VID_STATUS IN ('IN', 'OUT', 'LOST'))


--46
UPDATE VIDEO
SET VID_STATUS = 'OUT'
WHERE VID_NUM IN (SELECT VID_NUM
			  FROM DETAILRENTAL
			  WHERE DETAIL_RETURNDATE IS NULL)


--47
ALTER TABLE PRICE
ADD PRICE_RENTDAYS DECIMAL(2) NOT NULL DEFAULT 3


--48
SELECT * FROM PRICE

UPDATE PRICE
SET PRICE_RENTDAYS = 5
WHERE PRICE_CODE = 1

UPDATE PRICE
SET PRICE_RENTDAYS = 3
WHERE PRICE_CODE = 2

UPDATE PRICE
SET PRICE_RENTDAYS = 5
WHERE PRICE_CODE = 3

UPDATE PRICE
SET PRICE_RENTDAYS = 7
WHERE PRICE_CODE = 4


--52  

--THIS EXECUTION WILL RETURN AN ERROR
EXEC PRC_NEW_RENTAL 101

--THIS EXECUTION WILL RETURN THE BALANCE FOR 102
EXEC PRC_NEW_RENTAL 102
--RUN THIS WITH ABOVE EXECUTION TO VERIFY
SELECT * FROM MEMBERSHIP WHERE MEM_NUM = 102

--THIS WILL ALLOW YOU TO CHECK TO MAKE SURE IT HAS BEEN ENTERED INTO THE RENTAL TABLE
SELECT * FROM RENTAL

