--44
SELECT DEPT_NAME
FROM LGDEPARTMENT

--45
SELECT PROD_SKU, PROD_DESCRIPT, PROD_TYPE, PROD_BASE, PROD_CATEGORY, PROD_PRICE
FROM LGPRODUCT
WHERE PROD_BASE = 'WATER' and PROD_CATEGORY = 'SEALER'

--46
SELECT EMP_FNAME, EMP_LNAME, EMP_EMAIL
FROM LGEMPLOYEE
WHERE EMP_HIREDATE BETWEEN  '1/1/2001' AND '12/31/2010'
ORDER BY EMP_LNAME, EMP_FNAME

--47
SELECT EMP_FNAME, EMP_LNAME, EMP_PHONE, EMP_TITLE, DEPT_NUM
FROM LGEMPLOYEE
WHERE DEPT_NUM = 300 OR EMP_TITLE = 'CLERK I'
ORDER BY EMP_LNAME, EMP_FNAME

--48
SELECT E.EMP_NUM, E.EMP_LNAME, E.EMP_FNAME, H.SAL_FROM, H.SAL_END, H.SAL_AMOUNT
FROM LGEMPLOYEE E INNER JOIN LGSALARY_HISTORY H ON E.EMP_NUM = H.EMP_NUM
WHERE E.EMP_NUM = '83731' OR E.EMP_NUM = '83745' OR E.EMP_NUM = '84039'
ORDER BY E.EMP_NUM, H.SAL_FROM

--49  
SELECT DISTINCT C.CUST_FNAME, C.CUST_LNAME, C.CUST_STREET, C.CUST_CITY, C.CUST_STATE, C.CUST_ZIP
FROM LGCUSTOMER C INNER JOIN LGINVOICE I ON C.CUST_CODE = I.CUST_CODE INNER JOIN LGLINE L ON I.INV_NUM= L.INV_NUM 
		INNER JOIN LGPRODUCT P ON L.PROD_SKU = P.PROD_SKU INNER JOIN LGBRAND B ON P.BRAND_ID = B.BRAND_ID
WHERE B.BRAND_NAME = 'FORESTERS BEST' AND P.PROD_CATEGORY = 'TOP COAT' AND I.INV_DATE > '7-15-2011' AND I.INV_DATE <= '7-31-2011'
ORDER BY C.CUST_STATE, C.CUST_LNAME, C.CUST_FNAME


--50   
SELECT E.EMP_NUM, E.EMP_LNAME, E. EMP_EMAIL, E.EMP_TITLE, D.DEPT_NAME
FROM LGEMPLOYEE E INNER JOIN LGDEPARTMENT D ON E.DEPT_NUM = D.DEPT_NUM
--WHERE E.EMP_TITLE LIKE '%Associate'
WHERE E.EMP_TITLE LIKE '% ASSOCIATE' OR E.EMP_TITLE = 'ASSOCIATE'
ORDER BY  D.DEPT_NAME, E.EMP_TITLE


--51 
SELECT DISTINCT B.BRAND_NAME, COUNT(P.PROD_QOH) AS NUMPRODUCTS
FROM LGBRAND B INNER JOIN LGPRODUCT P ON B.BRAND_ID = P.BRAND_ID
GROUP BY B.BRAND_NAME


--52
SELECT DISTINCT P.PROD_CATEGORY, COUNT(P.PROD_QOH) AS NUMPRODUCTS
FROM LGPRODUCT P
WHERE P.PROD_BASE = 'WATER'
GROUP BY P.PROD_CATEGORY


--53
SELECT P.PROD_BASE, P.PROD_TYPE, COUNT(P.PROD_QOH) AS NUMPRODUCTS
FROM LGPRODUCT P
GROUP BY P.PROD_BASE, P.PROD_TYPE
ORDER BY P.PROD_BASE


--54
SELECT DISTINCT B.BRAND_ID, SUM(P.PROD_QOH) AS TOTALINVENTORY
FROM LGBRAND B INNER JOIN LGPRODUCT P ON B.BRAND_ID = P.BRAND_ID
GROUP BY B.BRAND_ID
ORDER BY B.BRAND_ID DESC


--55
SELECT B.BRAND_ID, B.BRAND_NAME, ROUND(AVG(P.PROD_PRICE),2) AS AVGPRICE
FROM LGBRAND B INNER JOIN LGPRODUCT P ON B.BRAND_ID = P.BRAND_ID
GROUP BY B.BRAND_NAME, B.BRAND_ID
ORDER BY B.BRAND_NAME


--56
SELECT D.DEPT_NUM, MAX(E.EMP_HIREDATE) AS MOSTRECENT
FROM LGDEPARTMENT D INNER JOIN LGEMPLOYEE E ON D.DEPT_NUM = E.DEPT_NUM
GROUP BY D.DEPT_NUM
ORDER BY D.DEPT_NUM


--57
SELECT E.EMP_NUM, E.EMP_FNAME, E.EMP_LNAME, MAX(H.SAL_AMOUNT) AS LARGESTSALARY
FROM LGEMPLOYEE E INNER JOIN LGSALARY_HISTORY H ON E.EMP_NUM = H.EMP_NUM
WHERE E.DEPT_NUM = '200'
GROUP BY E.EMP_NUM, E.EMP_FNAME, E.EMP_LNAME
ORDER BY LARGESTSALARY DESC

--58 
SELECT C.CUST_CODE, C.CUST_FNAME, C.CUST_LNAME, SUM(I.INV_TOTAL) AS TOTALINVOICES
FROM LGCUSTOMER C INNER JOIN LGINVOICE I ON C.CUST_CODE = I.CUST_CODE
GROUP BY C.CUST_CODE, C.CUST_FNAME, C.CUST_LNAME
HAVING SUM(I.INV_TOTAL) > 1500
ORDER BY TOTALINVOICES DESC

--59 
SELECT D.DEPT_NUM, D.DEPT_NAME, D.DEPT_PHONE, D.EMP_NUM, E.EMP_LNAME
FROM LGDEPARTMENT D INNER JOIN LGEMPLOYEE E ON D.EMP_NUM = E.EMP_NUM
ORDER BY D.DEPT_NAME


--60
SELECT V.VEND_ID, V.VEND_NAME, B.BRAND_NAME, COUNT(P.PROD_QOH)
FROM LGVENDOR V INNER JOIN LGSUPPLIES S ON V.VEND_ID = S.VEND_ID INNER JOIN LGPRODUCT P
	ON S.PROD_SKU = P.PROD_SKU INNER JOIN LGBRAND B ON P.BRAND_ID = B.BRAND_ID
GROUP BY V.VEND_ID, V.VEND_NAME, B.BRAND_NAME
ORDER BY V.VEND_NAME, B.BRAND_NAME


--61
SELECT E.EMP_NUM, E.EMP_LNAME, E.EMP_FNAME, SUM(I.INV_TOTAL) AS TOTALINVOICES
FROM LGEMPLOYEE E INNER JOIN LGINVOICE I ON E.EMP_NUM = I.EMPLOYEE_ID
GROUP BY E.EMP_NUM, E.EMP_LNAME, E.EMP_FNAME
ORDER BY E.EMP_LNAME, E.EMP_FNAME

--62      DISPLAYS AN INCORRECT VALUE      GROUP BY BRAND
CREATE VIEW AVG_PROD_PRICE
AS
SELECT BRAND_ID, AVG(PROD_PRICE) AS AVERAGE_PRICE
FROM LGPRODUCT
GROUP BY  BRAND_ID


SELECT MAX(AVERAGE_PRICE) AS [LARGEST AVERAGE]
FROM AVG_PROD_PRICE


--63   WORKS, BUT "CREATE VIEW" RETURNS WRONG INFO
SELECT B.BRAND_ID, B.BRAND_NAME, MAX(AVERAGE_PRICE)
FROM AVG_PROD_PRICE, LGBRAND B 
GROUP BY B.BRAND_ID, B.BRAND_NAME


--64 
CREATE VIEW MANAGER_NAME
AS
SELECT D.EMP_NUM, e.EMP_FNAME + ' ' + E.EMP_LNAME AS [MANAGER NAME]
FROM LGDEPARTMENT D INNER JOIN LGEMPLOYEE E ON D.DEPT_NUM = E.DEPT_NUM
WHERE D.EMP_NUM = E.EMP_NUM
GROUP BY D.EMP_NUM, E.EMP_FNAME, E.EMP_LNAME 

SELECT M.[MANAGER NAME], D.DEPT_NAME, D.DEPT_PHONE, E.EMP_FNAME + ' ' + E.EMP_LNAME AS EMPLOYEE_NAME,
	   C.CUST_FNAME + ' ' + C.CUST_LNAME AS CUSTOMER_NAME, I.INV_DATE, I.INV_TOTAL	
FROM MANAGER_NAME M INNER JOIN LGDEPARTMENT D ON M.EMP_NUM = D.EMP_NUM INNER JOIN LGEMPLOYEE E ON D.DEPT_NUM = E.DEPT_NUM
	 INNER JOIN LGINVOICE I ON E.EMP_NUM = I.EMPLOYEE_ID INNER JOIN LGCUSTOMER C ON I.CUST_CODE = C.CUST_CODE
WHERE C.CUST_LNAME = 'HAGAN' AND I.INV_DATE = '5-18-2011'
	 			   