--Nicholas Schuler
--CIS 31029

CREATE TRIGGER [DBO].[A9]
   ON [DBO].[LGLINE]
   AFTER INSERT,DELETE,UPDATE
AS 
BEGIN
	DECLARE @CUSTOMER_NUM INT
	DECLARE @TOTAL INT

	--INSERT CASE
	IF(EXISTS(SELECT * FROM INSERTED) AND NOT EXISTS (SELECT * FROM DELETED))
	BEGIN
		DECLARE INSERT_CURSOR CURSOR FOR
		SELECT PROD_SKU, SUM(LINE_QTY*LINE_PRICE) AS TOTAL  --WILL THIS SUM WORK?
		--OR SELECT PROD_SKU, SUM(LINE_PRICE) AS TOTAL
		FROM INSERTED
		GROUP BY PROD_SKU

		OPEN INSERT_CURSOR
		FETCH NEXT FROM INSERT_CURSOR INTO @CUSTOMER_NUM, @TOTAL
		WHILE (@@FETCH_STATUS = 0)
		BEGIN
			UPDATE LGINVOICE
			SET INV_TOTAL = INV_TOTAL + @TOTAL
			WHERE CUST_CODE = @CUSTOMER_NUM
			FETCH NEXT FROM INSERT_CURSOR INTO @CUSTOMER_NUM, @TOTAL

			UPDATE LGCUSTOMER
			SET CUST_BALANCE = CUST_BALANCE + @TOTAL
			WHERE CUST_CODE = @CUSTOMER_NUM
			FETCH NEXT FROM INSERT_CURSOR INTO @CUSTOMER_NUM, @TOTAL
		END 
		CLOSE INSERT_CURSOR
		DEALLOCATE INSERT_CURSOR
	END

	--DELETE CASE
	IF(EXISTS(SELECT * FROM DELETED) AND NOT EXISTS (SELECT * FROM INSERTED))
	BEGIN
		DECLARE DELETE_CURSOR CURSOR FOR
		SELECT PROD_SKU, SUM(LINE_QTY*LINE_PRICE) AS TOTAL    --WILL THIS SUM WORK?
		FROM DELETED
		GROUP BY PROD_SKU

		OPEN DELETE_CURSOR
		FETCH NEXT FROM DELETE_CURSOR INTO @CUSTOMER_NUM, @TOTAL
		WHILE (@@FETCH_STATUS = 0)
		BEGIN
			UPDATE LGINVOICE
			SET INV_TOTAL = INV_TOTAL - @TOTAL
			WHERE CUST_CODE = @CUSTOMER_NUM
			FETCH NEXT FROM DELETE_CURSOR INTO @CUSTOMER_NUM, @TOTAL

			UPDATE LGCUSTOMER
			SET CUST_BALANCE = CUST_BALANCE - @TOTAL
			WHERE CUST_CODE = @CUSTOMER_NUM
			FETCH NEXT FROM DELETE_CURSOR INTO @CUSTOMER_NUM, @TOTAL
		END
		CLOSE DELETE_CURSOR
		DEALLOCATE DELETE_CUSOR
	END


	--UPDATE CASE
	IF(EXISTS (SELECT * FROM DELETED) AND EXISTS (SELECT * FROM INSERTED))
	BEGIN
		DECLARE UPDATE_CURSOR CURSOR FOR
		SELECT I.PROD_SKU, SUM((I.LINE_QTY*I.LINE_PRICE)-(D.LINE_QTY*D.LINE_PRICE)) AS TOTAL
		FROM DELETED D INNER JOIN INSERTED I ON D.PROD_SKU = I.PROD_SKU AND D.INV_NUM = I.INV_NUM
		GROUP BY I.PROD_SKU

		OPEN UPDATE_CURSOR
		FETCH NEXT FROM UPDATE_CURSOR INTO @CUSTOMER_NUM, @TOTAL
		WHILE (@@FETCH_STATUS = 0)
		BEGIN
			UPDATE LGINVOICE
			SET INV_TOTAL = INV_TOTAL - @TOTAL
			WHERE CUST_CODE = @CUSTOMER_NUM
			FETCH NEXT FROM UPDATE_CURSOR INTO @CUSTOMER_NUM, @TOTAL

			UPDATE LGCUSTOMER
			SET CUST_BALANCE = CUST_BALANCE - @TOTAL
			WHERE CUST_CODE = @CUSTOMER_NUM
			FETCH NEXT FROM UPDATE_CURSOR INTO @CUSTOMER_NUM, @TOTAL
		END
		CLOSE UPDATE_CURSOR
		DEALLOCATE UPDATE_CURSOR
	END
END

