--Nicholas Schuler
--CIS 31029


--SOME OF PART 3
--USE THIS TO SEE THE CUSTOMER BALANCE BEFORE THE UPDATE
SELECT CUST_CODE, CUST_BALANCE
FROM LGCUSTOMER
ORDER BY CUST_CODE


--CREATE VIEW TO GET THE SUM, SINCE AGGREGATE FUNCTIONS CANNOT BE IN AN UPDATE
CREATE VIEW INVOICE_TOTALS
AS
SELECT CUST_CODE, SUM(INV_TOTAL) AS [INVOICE TOTAL]
FROM LGINVOICE
GROUP BY CUST_CODE



--PART 1

--UPDATE THE LGCUSTOMER TABLE TO MATCH THE INVOICE TOTALS, USING CREATE VIEW ABOVE
UPDATE LGCUSTOMER
SET CUST_BALANCE = [INVOICE TOTAL]
FROM LGCUSTOMER C INNER JOIN INVOICE_TOTALS I ON C.CUST_CODE = I.CUST_CODE


--TO SEE WHAT THE SUMS ARE IN THE INVOICE TABLE
SELECT CUST_CODE, SUM(INV_TOTAL)
FROM LGINVOICE
GROUP BY CUST_CODE
ORDER BY CUST_CODE

--SOME OF PART 3
--DO THIS AGAIN TO SEE THE NEWLY UPDATED CUSTOMER BALANCE
SELECT CUST_CODE, CUST_BALANCE
FROM LGCUSTOMER
ORDER BY CUST_CODE

-----------------------------------------------

--PART 2

SELECT * 
FROM LGINVOICE 
WHERE CUST_CODE = 88 and INV_NUM = 104

SELECT * 
FROM LGLINE 
WHERE INV_NUM = 104


UPDATE LGLINE
SET LINE_PRICE = 50
WHERE INV_NUM = 104 and PROD_SKU = '8523-UCB'    
